import authPerson from './auth-person.svg';
import bmstuLogo from './bmstu.svg';
import sidemenu from './dots.svg';
import file from './file.svg';
import folder from './folder.svg';
import garbage from './garbage.svg';
import list from './menu.svg';
import paper from './paper.svg';
import telegramLogo from './telegram.svg';
import tile from './tile.svg';
import trash from './trash.svg';
import upload from './upload.svg';

export const BMSTUIcon = bmstuLogo;
export const FolderIcon = folder;
export const TelegramIcon = telegramLogo;
export const FileIcon = file;
export const TileIcon = tile;
export const ListIcon = list;
export const MenuIcon = sidemenu;
export const AuhtPersonIcon = authPerson;
export const GarbageIcon = garbage;
export const UploadIcon = upload;
export const PaperClipIcon = paper;
export const TrashIcon = trash;
